name: Test

on:
  push:
  pull_request:
    branches: [ $default-branch ]

jobs:
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node: [ '12', '14', '16' ]
      name: Node ${{ matrix.node }}
      steps:
        - uses: actions/checkout@v2
        - name: Setup node
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node }}
        - run: npm install
        - run: npm test
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v2
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            directory: ./coverage
            fail_ci_if_error: true
            name: codecov-umbrella
            verbose: true